# Generated by Django 5.2.12 on 2026-05-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已激活"), ("disabled", "已禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("code", models.TextField(verbose_name="工具代码")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "自定义工具",
                "verbose_name_plural": "自定义工具",
                "db_table": "tools_custom_tool",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="McpServerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已激活"), ("disabled", "已禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("sse", "SSE"),
                            ("stdio", "STDIO"),
                            ("http", "HTTP"),
                            ("websocket", "WebSocket"),
                        ],
                        default="sse",
                        max_length=20,
                        verbose_name="传输协议",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, default="", verbose_name="服务器 URL"),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="可执行命令",
                    ),
                ),
                (
                    "args",
                    models.JSONField(blank=True, default=list, verbose_name="命令参数"),
                ),
                (
                    "env",
                    models.JSONField(blank=True, default=dict, verbose_name="环境变量"),
                ),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "auth_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="认证 Token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Server 配置",
                "verbose_name_plural": "MCP Server 配置",
                "db_table": "tools_mcp_server_config",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="SkillConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已激活"), ("disabled", "已禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("pipeline", "管线模式"),
                            ("advisor", "顾问模式"),
                            ("hybrid", "混合模式"),
                        ],
                        default="pipeline",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="pipeline", max_length=20, verbose_name="类型"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="SkillStep 列表，每项包含 tool_name, args_template, condition",
                        verbose_name="执行步骤",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工具管道",
                "verbose_name_plural": "工具管道",
                "db_table": "tools_skill_config",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="SkillPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已激活"), ("disabled", "已禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="许可证"
                    ),
                ),
                (
                    "compatibility",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="兼容性要求",
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "allowed_tools",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="预批准工具列表",
                    ),
                ),
                (
                    "skill_dir",
                    models.CharField(
                        max_length=500, verbose_name="Skill 包文件系统路径"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system", "系统预置"),
                            ("user", "用户上传"),
                            ("marketplace", "市场安装"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill 技能包",
                "verbose_name_plural": "Skill 技能包",
                "db_table": "tools_skill_package",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
    ]
