# Generated by Django 5.2.12 on 2026-05-30 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillconfig",
            name="steps",
            field=models.JSONField(default=list, verbose_name="执行步骤"),
        ),
        migrations.CreateModel(
            name="ToolRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已激活"), ("disabled", "已禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("langchain", "LangChain 工具"),
                            ("mcp", "MCP 工具"),
                            ("skill", "Skill 技能"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="工具类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("system", "系统内置"), ("user", "用户上传")],
                        db_index=True,
                        default="user",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general", max_length=50, verbose_name="功能分类"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="工具配置"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工具注册表",
                "verbose_name_plural": "工具注册表",
                "db_table": "tools_registry",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tool_type", "source"], name="idx_tool_type_source"
                    ),
                    models.Index(
                        fields=["tool_type", "is_enabled"], name="idx_tool_type_enabled"
                    ),
                ],
                "unique_together": {("user", "tool_type", "name")},
            },
        ),
    ]
