# Generated by Django 5.2.12 on 2026-05-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_add_tool_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="图标"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "功能分类",
                "verbose_name_plural": "功能分类",
                "db_table": "tools_category",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="customtool",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "系统内置"),
                    ("user", "用户上传"),
                    ("marketplace", "市场安装"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="customtool",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("langchain", "LangChain 工具"),
                    ("mcp", "MCP 工具"),
                    ("skill", "Skill 工具"),
                ],
                db_index=True,
                default="langchain",
                max_length=20,
                verbose_name="工具类型",
            ),
        ),
        migrations.AddField(
            model_name="mcpserverconfig",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "系统内置"),
                    ("user", "用户上传"),
                    ("marketplace", "市场安装"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="mcpserverconfig",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("langchain", "LangChain 工具"),
                    ("mcp", "MCP 工具"),
                    ("skill", "Skill 工具"),
                ],
                db_index=True,
                default="langchain",
                max_length=20,
                verbose_name="工具类型",
            ),
        ),
        migrations.AddField(
            model_name="skillconfig",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "系统内置"),
                    ("user", "用户上传"),
                    ("marketplace", "市场安装"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="skillconfig",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("langchain", "LangChain 工具"),
                    ("mcp", "MCP 工具"),
                    ("skill", "Skill 工具"),
                ],
                db_index=True,
                default="langchain",
                max_length=20,
                verbose_name="工具类型",
            ),
        ),
        migrations.AddField(
            model_name="skillpackage",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("langchain", "LangChain 工具"),
                    ("mcp", "MCP 工具"),
                    ("skill", "Skill 工具"),
                ],
                db_index=True,
                default="langchain",
                max_length=20,
                verbose_name="工具类型",
            ),
        ),
        migrations.AlterField(
            model_name="skillconfig",
            name="steps",
            field=models.JSONField(
                default=list,
                help_text="SkillStep 列表，每项包含 tool_name, args_template, condition",
                verbose_name="执行步骤",
            ),
        ),
        migrations.AlterField(
            model_name="skillpackage",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "系统内置"),
                    ("user", "用户上传"),
                    ("marketplace", "市场安装"),
                ],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="customtool",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tools.toolcategory",
                verbose_name="功能分类",
            ),
        ),
        migrations.AddField(
            model_name="mcpserverconfig",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tools.toolcategory",
                verbose_name="功能分类",
            ),
        ),
        migrations.AddField(
            model_name="skillconfig",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tools.toolcategory",
                verbose_name="功能分类",
            ),
        ),
        migrations.AddField(
            model_name="skillpackage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="tools.toolcategory",
                verbose_name="功能分类",
            ),
        ),
        migrations.DeleteModel(
            name="ToolRegistry",
        ),
    ]
