# Generated by Django 5.2.12 on 2026-07-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_encrypt_mcp_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtool",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
    ]
