# Generated by Django 5.2.12 on 2026-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="current_step",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="当前步骤"
            ),
        ),
    ]
