# Generated by Django 5.2.12 on 2026-05-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "chat_sessions",
                    models.PositiveIntegerField(default=0, verbose_name="聊天会话数"),
                ),
                (
                    "chat_messages",
                    models.PositiveIntegerField(default=0, verbose_name="聊天消息数"),
                ),
                (
                    "chat_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="聊天Token数"),
                ),
                (
                    "chat_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="聊天成本",
                    ),
                ),
                (
                    "rag_queries",
                    models.PositiveIntegerField(default=0, verbose_name="RAG查询数"),
                ),
                (
                    "documents_uploaded",
                    models.PositiveIntegerField(default=0, verbose_name="上传文档数"),
                ),
                (
                    "documents_deleted",
                    models.PositiveIntegerField(default=0, verbose_name="删除文档数"),
                ),
                (
                    "workflow_started",
                    models.PositiveIntegerField(default=0, verbose_name="启动工作流数"),
                ),
                (
                    "workflow_completed",
                    models.PositiveIntegerField(default=0, verbose_name="完成工作流数"),
                ),
                (
                    "research_started",
                    models.PositiveIntegerField(default=0, verbose_name="启动研究数"),
                ),
                (
                    "research_completed",
                    models.PositiveIntegerField(default=0, verbose_name="完成研究数"),
                ),
                (
                    "file_uploads",
                    models.PositiveIntegerField(default=0, verbose_name="文件上传数"),
                ),
                (
                    "file_downloads",
                    models.PositiveIntegerField(default=0, verbose_name="文件下载数"),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(default=0, verbose_name="页面浏览数"),
                ),
                (
                    "api_requests",
                    models.PositiveIntegerField(default=0, verbose_name="API请求数"),
                ),
                (
                    "api_errors",
                    models.PositiveIntegerField(default=0, verbose_name="API错误数"),
                ),
                (
                    "avg_response_time_ms",
                    models.FloatField(default=0, verbose_name="平均响应时间(ms)"),
                ),
                (
                    "login_count",
                    models.PositiveIntegerField(default=0, verbose_name="登录次数"),
                ),
                (
                    "feature_usage",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="功能使用详情"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_daily_aggregations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日统计汇总",
                "verbose_name_plural": "每日统计汇总",
                "db_table": "analytics_daily_aggregation",
                "indexes": [
                    models.Index(fields=["date"], name="analytics_d_date_d023b7_idx"),
                    models.Index(
                        fields=["user", "-date"], name="analytics_d_user_id_f21067_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("chat.message.send", "发送聊天消息"),
                            ("chat.message.receive", "接收AI回复"),
                            ("chat.session.create", "创建会话"),
                            ("chat.session.delete", "删除会话"),
                            ("chat.mode.switch", "切换对话模式"),
                            ("rag.query", "RAG检索查询"),
                            ("rag.index.create", "创建索引"),
                            ("rag.index.delete", "删除索引"),
                            ("rag.document.upload", "上传文档"),
                            ("rag.document.delete", "删除文档"),
                            ("knowledge.base.access", "访问知识库"),
                            ("workflow.start", "启动工作流"),
                            ("workflow.submit", "提交工作流答案"),
                            ("workflow.complete", "完成工作流"),
                            ("research.start", "启动研究"),
                            ("research.complete", "完成研究"),
                            ("file.upload", "文件上传"),
                            ("file.download", "文件下载"),
                            ("file.delete", "文件删除"),
                            ("auth.login", "用户登录"),
                            ("auth.logout", "用户登出"),
                            ("auth.register", "用户注册"),
                            ("page.view", "页面浏览"),
                            ("api.request", "API请求"),
                            ("feature.use", "功能使用"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("chat", "智能聊天"),
                            ("rag", "RAG检索"),
                            ("knowledge", "知识库"),
                            ("workflow", "学习工作流"),
                            ("research", "深度研究"),
                            ("file", "文件操作"),
                            ("auth", "认证"),
                            ("page_view", "页面浏览"),
                            ("api_call", "API调用"),
                            ("system", "系统"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="事件分类",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="会话ID"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="资源ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="资源类型"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="事件元数据"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="用户代理"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="耗时(毫秒)"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户事件",
                "verbose_name_plural": "用户事件",
                "db_table": "analytics_user_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_u_user_id_ba53d8_idx",
                    ),
                    models.Index(
                        fields=["event_category", "-created_at"],
                        name="analytics_u_event_c_1d3ddd_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="analytics_u_event_t_465709_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_f37a70_idx"
                    ),
                    models.Index(
                        fields=["event_category", "event_type"],
                        name="analytics_u_event_c_19c0c6_idx",
                    ),
                ],
            },
        ),
    ]
