# Generated by Django 5.2.12 on 2026-05-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyaggregation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_daily_aggregations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyaggregation",
            index=models.Index(fields=["date"], name="analytics_d_date_d023b7_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyaggregation",
            index=models.Index(
                fields=["user", "-date"], name="analytics_d_user_id_f21067_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyaggregation",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["user", "-created_at"], name="analytics_u_user_id_ba53d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["event_category", "-created_at"],
                name="analytics_u_event_c_1d3ddd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="analytics_u_event_t_465709_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["created_at"], name="analytics_u_created_f37a70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["event_category", "event_type"],
                name="analytics_u_event_c_19c0c6_idx",
            ),
        ),
    ]
