# Generated by Django 5.2.12 on 2026-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyaggregation",
            name="chat_cost",
        ),
        migrations.AddField(
            model_name="dailyaggregation",
            name="chat_token_detail",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="聊天Token明细"
            ),
        ),
    ]
