# Generated by Django 5.2.12 on 2026-08-19 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_token_detail_replace_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dailyaggregation",
            name="analytics_d_date_d023b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailyaggregation",
            name="analytics_d_user_id_f21067_idx",
        ),
        migrations.RemoveIndex(
            model_name="userevent",
            name="analytics_u_created_f37a70_idx",
        ),
        migrations.AlterField(
            model_name="dailyaggregation",
            name="user",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_daily_aggregations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="event_category",
            field=models.CharField(
                choices=[
                    ("chat", "智能聊天"),
                    ("rag", "RAG检索"),
                    ("knowledge", "知识库"),
                    ("workflow", "学习工作流"),
                    ("research", "深度研究"),
                    ("file", "文件操作"),
                    ("auth", "认证"),
                    ("page_view", "页面浏览"),
                    ("api_call", "API调用"),
                    ("system", "系统"),
                ],
                max_length=20,
                verbose_name="事件分类",
            ),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("chat.message.send", "发送聊天消息"),
                    ("chat.message.receive", "接收AI回复"),
                    ("chat.session.create", "创建会话"),
                    ("chat.session.delete", "删除会话"),
                    ("chat.mode.switch", "切换对话模式"),
                    ("rag.query", "RAG检索查询"),
                    ("rag.index.create", "创建索引"),
                    ("rag.index.delete", "删除索引"),
                    ("rag.document.upload", "上传文档"),
                    ("rag.document.delete", "删除文档"),
                    ("knowledge.base.access", "访问知识库"),
                    ("workflow.start", "启动工作流"),
                    ("workflow.submit", "提交工作流答案"),
                    ("workflow.complete", "完成工作流"),
                    ("research.start", "启动研究"),
                    ("research.complete", "完成研究"),
                    ("file.upload", "文件上传"),
                    ("file.download", "文件下载"),
                    ("file.delete", "文件删除"),
                    ("auth.login", "用户登录"),
                    ("auth.logout", "用户登出"),
                    ("auth.register", "用户注册"),
                    ("page.view", "页面浏览"),
                    ("api.request", "API请求"),
                    ("feature.use", "功能使用"),
                ],
                max_length=50,
                verbose_name="事件类型",
            ),
        ),
        migrations.AlterField(
            model_name="userevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
