# Generated by Django 5.2.12 on 2026-05-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                ("query", models.TextField(verbose_name="研究主题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("final_report", models.TextField(blank=True, verbose_name="最终报告")),
                (
                    "enable_web_search",
                    models.BooleanField(default=True, verbose_name="启用网络搜索"),
                ),
                (
                    "enable_doc_analysis",
                    models.BooleanField(default=False, verbose_name="启用文档分析"),
                ),
                (
                    "knowledge_base_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关联知识库ID列表"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="关联会话ID",
                    ),
                ),
                (
                    "research_depth",
                    models.CharField(
                        choices=[
                            ("basic", "基础"),
                            ("standard", "标准"),
                            ("comprehensive", "综合"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="研究深度",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="使用的模型"
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(default=0, verbose_name="Token 数量"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="成本(美元)",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(default=0, verbose_name="响应时间(秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究任务",
                "verbose_name_plural": "研究任务",
                "db_table": "research_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="research_ta_status_16d700_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="research_ta_created_c1bdc0_idx",
                    ),
                ],
            },
        ),
    ]
