# Generated by Django 5.2.12 on 2026-05-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_token_detail_replace_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_tasks",
                to="research.researchtask",
                verbose_name="父级研究任务",
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="version",
            field=models.IntegerField(default=1, verbose_name="版本号"),
        ),
    ]
