# Generated by Django 5.2.12 on 2026-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_add_parent_task_and_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="selected_mcp_servers",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的MCP服务器"
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="selected_tools",
            field=models.JSONField(blank=True, default=list, verbose_name="选中的工具"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="use_mcp",
            field=models.BooleanField(default=False, verbose_name="启用MCP"),
        ),
    ]
