# Generated by Django 5.2.12 on 2026-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_alter_researchtask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="enable_deep_thinking",
            field=models.BooleanField(default=False, verbose_name="是否启用深度思考"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="max_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最大 token 数"
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="model_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="模型名称"
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="provider_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="模型提供商 ID"
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="special_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="特殊参数"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="温度参数"),
        ),
    ]
