# Generated by Django 5.2.12 on 2026-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_researchtask_enable_deep_thinking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="chat_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="关联聊天消息ID",
            ),
        ),
    ]
