# Generated by Django 5.2.12 on 2026-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_researchtask_chat_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="approval_history",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="对象结构，key=interrupt_id，value=审批详情",
                verbose_name="审批历史",
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="tool_calls",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="对象结构，key=tool_call_id，value=工具调用详情",
                verbose_name="工具调用历史",
            ),
        ),
    ]
