# Generated by Django 5.2.12 on 2026-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_researchtask_approval_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchtask",
            name="approval_history",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="chat_message_id",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="enable_deep_thinking",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="max_tokens",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="provider_id",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="special_params",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="researchtask",
            name="tool_calls",
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="token_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Token 数量"),
        ),
    ]
