# Generated by Django 5.2.12 on 2026-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0010_researchtask_tool_calls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
