# Generated by Django 5.2.12 on 2026-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0011_alter_researchtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="tool_calls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="数组结构，每个元素为工具调用详情对象，与 ChatMessage.tool_calls 格式一致",
                verbose_name="工具调用历史",
            ),
        ),
    ]
