# Generated by Django 5.2.12 on 2026-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0012_unify_tool_calls_to_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("awaiting_approval", "等待审批"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
