# Generated by Django 5.2.12 on 2026-08-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0013_add_awaiting_approval_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchtask",
            name="celery_task_id",
        ),
    ]
