# Generated by Django 5.2.12 on 2026-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0014_remove_researchtask_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="subagent_contents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="字典结构，key 为 subagent_thread_id，value 为 {content, reasoning_content}，与 ChatMessage.subagent_contents 格式一致",
                null=True,
                verbose_name="子代理正文累计",
            ),
        ),
    ]
