# Generated by Django 5.2.12 on 2026-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0015_researchtask_subagent_contents"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="content",
            field=models.TextField(
                blank=True, default="", verbose_name="主代理过程正文"
            ),
        ),
    ]
