# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0016_researchtask_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="enable_sandbox",
            field=models.BooleanField(default=False, verbose_name="启用沙箱执行"),
        ),
    ]
