# Generated by Django 5.2.12 on 2026-08-19 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approval_user(apps, schema_editor):
    """通过三路关联回填 Approval.user 字段。

    自 0009_add_user_field 内联（数字开头模块无法被 import）。
    优先级：chat_session_id > deep_research > learning。
    仅回填可确定归属的记录；无法确定归属的保留 NULL，由 fallback 处理。

    回填路径（参考 apps/approvals/views.py:_user_owns_approval 的三路分支）：
    1. chat_session_id → ChatSession.session_id → ChatSession.user
    2. source='deep_research' 时 source_id → ResearchTask.task_id → ResearchTask.created_by
    3. source='learning' 时 source_id → WorkflowSession.thread_id → WorkflowSession.created_by
    """
    Approval = apps.get_model('approvals', 'Approval')
    ChatSession = apps.get_model('chat', 'ChatSession')
    ResearchTask = apps.get_model('research', 'ResearchTask')
    WorkflowSession = apps.get_model('learning', 'WorkflowSession')

    pending = Approval.objects.filter(user__isnull=True)
    for approval in pending.iterator():
        owner_id = None

        # 路径 1：chat_session_id → ChatSession.user
        if approval.chat_session_id:
            cs = (
                ChatSession.objects.filter(session_id=approval.chat_session_id)
                .exclude(user__isnull=True)
                .first()
            )
            if cs is not None:
                owner_id = cs.user_id

        # 路径 2：source='deep_research' → ResearchTask.created_by
        if owner_id is None and approval.source == 'deep_research':
            rt = (
                ResearchTask.objects.filter(task_id=approval.source_id)
                .exclude(created_by__isnull=True)
                .first()
            )
            if rt is not None:
                owner_id = rt.created_by_id

        # 路径 3：source='learning' → WorkflowSession.created_by
        if owner_id is None and approval.source == 'learning':
            ws = (
                WorkflowSession.objects.filter(thread_id=approval.source_id)
                .exclude(created_by__isnull=True)
                .first()
            )
            if ws is not None:
                owner_id = ws.created_by_id

        if owner_id is not None:
            approval.user_id = owner_id
            approval.save(update_fields=['user'])


def noop_reverse(apps, schema_editor):
    """回滚不还原数据，仅由 RemoveField 处理字段移除。"""
    pass


class Migration(migrations.Migration):

    replaces = [('approvals', '0001_initial'), ('approvals', '0002_rename_approvals_source_source_id_idx_approvals_a_source_3872e0_idx_and_more'), ('approvals', '0003_alter_approval_operation'), ('approvals', '0004_approval_approved_by'), ('approvals', '0005_add_waiting_state'), ('approvals', '0006_alter_approval_source'), ('approvals', '0007_remove_approval_llm_tool_call_id'), ('approvals', '0008_approval_expires_at_and_more'), ('approvals', '0009_add_user_field'), ('approvals', '0010_approval_approval_src_state_created_idx'), ('approvals', '0011_approvaloutboxentry'), ('approvals', '0012_rename_approval_outbox_state_retry_idx_approvals_a_state_c6aaed_idx_and_more'), ('approvals', '0013_alter_approval_source')]

    initial = True

    dependencies = [
        ('chat', '0013_add_selected_tools_to_session'),
        ('learning', '0008_alter_workflowsession_knowledge_base_ids_and_more'),
        ('research', '0008_researchtask_approval_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interrupt_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('deep_research', 'Deep Research')], max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('chat_session_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('tool_name', models.CharField(max_length=128)),
                ('title', models.CharField(default='', max_length=256)),
                ('description', models.TextField(default='')),
                ('action', models.CharField(default='confirm', max_length=32)),
                ('operation', models.CharField(blank=True, default='', max_length=256)),
                ('danger_level', models.CharField(default='medium', max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('llm_tool_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=32)),
                ('user_input', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                # 索引名直接采用旧链路 RenameIndex 后的最终名：
                # PostgreSQL 下 CreateModel 的 Meta.indexes 走 deferred SQL，
                # 同一迁移内紧随其后的 RenameIndex（立即执行）会因索引尚未创建而失败，
                # 故将 0002/0012 的 RenameIndex 折叠进 CreateModel。
                'indexes': [models.Index(fields=['source', 'source_id'], name='approvals_a_source_3872e0_idx'), models.Index(fields=['chat_session_id', 'state'], name='approvals_a_chat_se_411569_idx'), models.Index(fields=['state', 'created_at'], name='approvals_a_state_dcef42_idx')],
            },
        ),
        migrations.AlterField(
            model_name='approval',
            name='operation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='approval',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('deep_research', 'Deep Research'), ('learning', 'Learning')], max_length=32),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='llm_tool_call_id',
        ),
        migrations.AddField(
            model_name='approval',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='创建时设置为 created_at + APPROVAL_TIMEOUT_SECONDS，供 Celery 任务判断', null=True, verbose_name='审批过期时间'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['state', 'expires_at'], name='approvals_a_state_32294c_idx'),
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批归属用户'),
        ),
        migrations.RunPython(
            code=backfill_approval_user,
            reverse_code=noop_reverse,
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['user', 'state', 'created_at'], name='approvals_a_user_id_df0012_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['source', 'state', 'created_at'], name='approval_src_state_created_idx'),
        ),
        migrations.CreateModel(
            name='ApprovalOutboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, verbose_name='事件类型')),
                ('payload', models.JSONField(default=dict, verbose_name='事件载荷')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='投递状态')),
                ('attempts', models.IntegerField(default=0, verbose_name='重试次数')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次重试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='投递时间')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='approvals.approval', verbose_name='关联审批')),
            ],
            options={
                'verbose_name': '审批发件箱条目',
                'verbose_name_plural': '审批发件箱条目',
                'ordering': ['created_at'],
                # 同上：0012 的两个 RenameIndex 已折叠为最终索引名。
                'indexes': [models.Index(fields=['state', 'next_retry_at'], name='approvals_a_state_c6aaed_idx'), models.Index(fields=['approval', 'event_type'], name='approvals_a_approva_2e4fc8_idx')],
            },
        ),
        migrations.AlterField(
            model_name='approval',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('deep_research', 'Deep Research')], max_length=32),
        ),
    ]
