# Generated by Django 5.2.12 on 2026-06-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="approval",
            new_name="approvals_a_source_3872e0_idx",
            old_name="approvals_source_source_id_idx",
        ),
        migrations.RenameIndex(
            model_name="approval",
            new_name="approvals_a_chat_se_411569_idx",
            old_name="approvals_chat_session_state_idx",
        ),
        migrations.RenameIndex(
            model_name="approval",
            new_name="approvals_a_state_dcef42_idx",
            old_name="approvals_state_created_at_idx",
        ),
    ]
