# Generated by Django 5.2.12 on 2026-07-03 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_alter_approval_operation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
    ]
