# Generated by Django 5.2.12 on 2026-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0004_approval_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("waiting", "Waiting"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("timeout", "Timeout"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
