# Generated by Django 5.2.12 on 2026-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0005_add_waiting_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="source",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("deep_research", "Deep Research"),
                    ("learning", "Learning"),
                ],
                max_length=32,
            ),
        ),
    ]
