# Generated by Django 5.2.12 on 2026-07-19 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0007_remove_approval_llm_tool_call_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approval",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="创建时设置为 created_at + APPROVAL_TIMEOUT_SECONDS，供 Celery 任务判断",
                null=True,
                verbose_name="审批过期时间",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["state", "expires_at"], name="approvals_a_state_32294c_idx"
            ),
        ),
    ]
