# Generated by Django 5.2.12 on 2026-07-27 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0009_add_user_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["source", "state", "created_at"],
                name="approval_src_state_created_idx",
            ),
        ),
    ]
