# Generated by Django 5.2.12 on 2026-07-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0011_approvaloutboxentry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="approvaloutboxentry",
            new_name="approvals_a_state_c6aaed_idx",
            old_name="approval_outbox_state_retry_idx",
        ),
        migrations.RenameIndex(
            model_name="approvaloutboxentry",
            new_name="approvals_a_approva_2e4fc8_idx",
            old_name="approval_outbox_apv_evt_idx",
        ),
    ]
