# Generated by Django 5.2.12 on 2026-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "approvals",
            "0012_rename_approval_outbox_state_retry_idx_approvals_a_state_c6aaed_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="source",
            field=models.CharField(
                choices=[("chat", "Chat"), ("deep_research", "Deep Research")],
                max_length=32,
            ),
        ),
    ]
