# Generated by Django 5.2.12 on 2026-05-27 08:06

import Django_xm.apps.attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttachmentCleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("cleanup", "定时清理"),
                            ("index", "入库"),
                            ("unindex", "移除入库"),
                            ("manual_delete", "手动删除"),
                            ("restore", "恢复"),
                            ("permanent_delete", "永久删除"),
                            ("restore_from_trash", "从回收站恢复"),
                        ],
                        default="cleanup",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "files_processed",
                    models.PositiveIntegerField(default=0, verbose_name="处理文件数"),
                ),
                (
                    "files_deleted",
                    models.PositiveIntegerField(default=0, verbose_name="删除文件数"),
                ),
                (
                    "files_archived",
                    models.PositiveIntegerField(default=0, verbose_name="入库文件数"),
                ),
                (
                    "files_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="跳过文件数"),
                ),
                (
                    "space_freed",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="释放空间(字节)"
                    ),
                ),
                (
                    "space_archived",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="入库空间(字节)"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="错误列表"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        default="system",
                        max_length=100,
                        verbose_name="触发来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "附件清理日志",
                "verbose_name_plural": "附件清理日志",
                "db_table": "chat_attachment_cleanup_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=Django_xm.apps.attachments.models.chat_attachment_upload_path,
                        verbose_name="文件",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("indexed", "已入库"),
                            ("pending_delete", "待删除"),
                            ("deleted", "已删除"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="附件状态",
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="最后访问时间"
                    ),
                ),
                (
                    "reference_count",
                    models.PositiveIntegerField(default=1, verbose_name="引用计数"),
                ),
                (
                    "indexed_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="向量索引路径",
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入库时间"
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="自定义保留天数"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="文件SHA256哈希",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天附件",
                "verbose_name_plural": "聊天附件",
                "db_table": "chat_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("critical", "严重")],
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="告警状态",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="存储路径"),
                ),
                (
                    "total_space",
                    models.PositiveBigIntegerField(verbose_name="总空间(字节)"),
                ),
                (
                    "used_space",
                    models.PositiveBigIntegerField(verbose_name="已用空间(字节)"),
                ),
                ("usage_percent", models.FloatField(verbose_name="使用率(%)")),
                ("threshold_percent", models.FloatField(verbose_name="阈值(%)")),
                ("message", models.TextField(blank=True, verbose_name="告警消息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "存储空间告警",
                "verbose_name_plural": "存储空间告警",
                "db_table": "chat_storage_alert",
                "ordering": ["-created_at"],
            },
        ),
    ]
