# Generated by Django 5.2.12 on 2026-05-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments", "0001_initial"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatmessage",
                verbose_name="消息",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatsession",
                verbose_name="会话",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddIndex(
            model_name="chatattachment",
            index=models.Index(
                fields=["status", "created_at"], name="chat_attach_status_6acc2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatattachment",
            index=models.Index(
                fields=["last_accessed_at"], name="chat_attach_last_ac_77829c_idx"
            ),
        ),
    ]
