# Generated by Django 5.2.12 on 2026-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentcleanuplog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="attachmentcleanuplog",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
        migrations.AddField(
            model_name="storagealert",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="storagealert",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
        migrations.AlterField(
            model_name="attachmentcleanuplog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="storagealert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
    ]
