# Generated by Django 5.2.12 on 2026-05-27 08:06

import Django_xm.apps.users.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="请输入有效的手机号", regex="^1[3-9]\\d{9}$"
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatar/", verbose_name="头像"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="light", max_length=20, verbose_name="主题"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-CN", max_length=10, verbose_name="语言"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(default=True, verbose_name="通知开关"),
                ),
                (
                    "auto_save_sessions",
                    models.BooleanField(default=True, verbose_name="自动保存会话"),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(default=0, verbose_name="总消息数"),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(default=0, verbose_name="总会话数"),
                ),
                (
                    "total_tokens",
                    models.PositiveBigIntegerField(default=0, verbose_name="总Token数"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="总费用",
                    ),
                ),
                (
                    "active_days",
                    models.PositiveIntegerField(default=0, verbose_name="活跃天数"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "langchain_users",
            },
            managers=[
                ("objects", Django_xm.apps.users.models.SoftDeleteUserManager()),
                ("all_objects", Django_xm.apps.users.models.AllUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserPermissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="为空表示全局策略",
                        max_length=100,
                        null=True,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("allow", "允许"),
                            ("deny", "拒绝"),
                            ("prompt", "提示确认"),
                        ],
                        default="allow",
                        max_length=20,
                        verbose_name="默认权限模式",
                    ),
                ),
                (
                    "session_mode",
                    models.CharField(
                        choices=[
                            ("read-only", "只读"),
                            ("workspace-write", "工作区写入"),
                            ("danger-full-access", "完全访问"),
                        ],
                        default="workspace-write",
                        max_length=30,
                        verbose_name="会话权限模式",
                    ),
                ),
                (
                    "tool_modes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='格式: {"tool_name": "allow/deny/prompt"}',
                        verbose_name="工具权限覆盖",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户权限策略",
                "verbose_name_plural": "用户权限策略",
                "db_table": "core_user_permission_policy",
                "indexes": [
                    models.Index(
                        fields=["user", "session_id"],
                        name="core_user_p_user_id_61eb03_idx",
                    )
                ],
                "unique_together": {("user", "session_id")},
            },
        ),
    ]
