# Generated by Django 5.2.12 on 2026-05-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userpermissionpolicy",
            new_name="users_user__user_id_3cdb07_idx",
            old_name="core_user_p_user_id_61eb03_idx",
        ),
        migrations.AlterModelTable(
            name="userpermissionpolicy",
            table="users_user_permission_policy",
        ),
    ]
