# Generated by Django 5.2.12 on 2026-04-05 16:49

import Django_xm.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", Django_xm.apps.users.models.SoftDeleteUserManager()),
                ("all_objects", Django_xm.apps.users.models.AllUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_time",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
    ]
