# Generated by Django 5.2.12 on 2026-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_days",
            field=models.PositiveIntegerField(default=0, verbose_name="活跃天数"),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_save_sessions",
            field=models.BooleanField(default=True, verbose_name="自动保存会话"),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="zh-CN", max_length=10, verbose_name="语言"),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications_enabled",
            field=models.BooleanField(default=True, verbose_name="通知开关"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(default="light", max_length=20, verbose_name="主题"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=12, verbose_name="总费用"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_messages",
            field=models.PositiveIntegerField(default=0, verbose_name="总消息数"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_sessions",
            field=models.PositiveIntegerField(default=0, verbose_name="总会话数"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_tokens",
            field=models.PositiveBigIntegerField(default=0, verbose_name="总Token数"),
        ),
    ]
