# Generated by Django 5.2.12 on 2026-05-30 00:53

import Django_xm.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_core_user_p_user_id_61eb03_idx_users_user__user_id_3cdb07_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Django_xm.apps.users.models.avatar_upload_path,
                verbose_name="头像",
            ),
        ),
        migrations.DeleteModel(
            name="UserPermissionPolicy",
        ),
    ]
