# Generated by Django 5.2.12 on 2026-04-05 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="更新时间",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            UPDATE langchain_users
            SET created_at = date_joined,
                updated_at = date_joined
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
