# Generated by Django 5.2.12 on 2026-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_permission_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="total_cost",
        ),
    ]
