# Generated by Django 5.2.12 on 2026-04-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="为空表示全局策略",
                        max_length=100,
                        null=True,
                        verbose_name="会话ID",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("allow", "允许"),
                            ("deny", "拒绝"),
                            ("prompt", "提示确认"),
                        ],
                        default="allow",
                        max_length=20,
                        verbose_name="默认权限模式",
                    ),
                ),
                (
                    "session_mode",
                    models.CharField(
                        choices=[
                            ("read-only", "只读"),
                            ("workspace-write", "工作区写入"),
                            ("danger-full-access", "完全访问"),
                        ],
                        default="workspace-write",
                        max_length=30,
                        verbose_name="会话权限模式",
                    ),
                ),
                (
                    "tool_modes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='格式: {"tool_name": "allow/deny/prompt"}',
                        verbose_name="工具权限覆盖",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_policies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户权限策略",
                "verbose_name_plural": "用户权限策略",
                "db_table": "core_user_permission_policy",
                "indexes": [
                    models.Index(
                        fields=["user", "session_id"],
                        name="core_user_p_user_id_61eb03_idx",
                    )
                ],
                "unique_together": {("user", "session_id")},
            },
        ),
    ]
