# Generated by Django 5.2.12 on 2026-07-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celerytaskrecord",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Celery 任务记录",
                "verbose_name_plural": "Celery 任务记录",
            },
        ),
    ]
