# Generated by Django 5.2.12 on 2026-04-29 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Celery 任务ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=255, verbose_name="任务名称"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("deep_research", "深度研究"),
                            ("rag_index", "RAG索引创建"),
                            ("rag_add_docs", "RAG文档添加"),
                            ("rag_delete_index", "RAG索引删除"),
                            ("workflow", "工作流执行"),
                            ("embedding", "向量化处理"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("started", "已开始"),
                            ("progress", "执行中"),
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("revoked", "已撤销"),
                            ("retry", "重试中"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "task_args",
                    models.JSONField(blank=True, default=dict, verbose_name="任务参数"),
                ),
                (
                    "task_kwargs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="任务关键字参数"
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="任务结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "progress_message",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="进度消息"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "runtime_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="运行时长(秒)"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "worker_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Worker 名称",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Celery 任务记录",
                "verbose_name_plural": "Celery 任务记录",
                "db_table": "core_celery_task_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "task_type"],
                        name="core_celery_status_042ae1_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"],
                        name="core_celery_created_8ce66a_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_celery_created_3a97a8_idx"
                    ),
                ],
            },
        ),
    ]
