# Generated by Django 5.2.12 on 2026-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_chat_task_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerytaskrecord",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("deep_research", "深度研究"),
                    ("rag_index", "RAG索引创建"),
                    ("rag_add_docs", "RAG文档添加"),
                    ("rag_delete_index", "RAG索引删除"),
                    ("rag_update_index", "RAG索引更新"),
                    ("workflow", "工作流执行"),
                    ("chat_cleanup", "附件清理"),
                    ("chat_index", "附件入库"),
                    ("chat_storage", "存储检查"),
                    ("other", "其他"),
                ],
                db_index=True,
                default="other",
                max_length=30,
                verbose_name="任务类型",
            ),
        ),
    ]
