# Generated by Django 5.2.12 on 2026-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                ("query", models.TextField(verbose_name="研究主题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("final_report", models.TextField(blank=True, verbose_name="最终报告")),
                (
                    "enable_web_search",
                    models.BooleanField(default=True, verbose_name="启用网络搜索"),
                ),
                (
                    "enable_doc_analysis",
                    models.BooleanField(default=False, verbose_name="启用文档分析"),
                ),
            ],
            options={
                "verbose_name": "研究任务",
                "verbose_name_plural": "研究任务",
                "db_table": "research_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="research_ta_status_16d700_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="research_ta_task_id_18f025_idx"
                    ),
                ],
            },
        ),
    ]
