# Generated by Django 5.2.12 on 2026-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deep_research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否已删除"
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
