# Generated by Django 5.2.12 on 2026-04-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deep_research",
            "0002_researchtask_deleted_at_researchtask_is_deleted_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="researchtask",
            name="celery_task_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Celery任务ID"
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="research_depth",
            field=models.CharField(
                choices=[
                    ("basic", "基础"),
                    ("standard", "标准"),
                    ("comprehensive", "综合"),
                ],
                default="standard",
                max_length=20,
                verbose_name="研究深度",
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddIndex(
            model_name="researchtask",
            index=models.Index(
                fields=["created_by", "status"], name="research_ta_created_c1bdc0_idx"
            ),
        ),
    ]
