# Generated by Django 5.2.12 on 2026-04-29 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="线程 ID"
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="工作流类型"
                    ),
                ),
                ("query", models.TextField(verbose_name="查询内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行",
                "verbose_name_plural": "工作流执行",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_type", "status", "-created_at"],
                        name="workflow_ex_workflo_22efda_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="线程 ID"
                    ),
                ),
                ("user_question", models.TextField(verbose_name="用户问题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("waiting_for_answers", "等待答案"),
                            ("retry", "重试"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="当前步骤"
                    ),
                ),
                (
                    "learning_plan",
                    models.JSONField(blank=True, null=True, verbose_name="学习计划"),
                ),
                (
                    "quiz",
                    models.JSONField(blank=True, null=True, verbose_name="练习题"),
                ),
                (
                    "user_answers",
                    models.JSONField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="得分"),
                ),
                (
                    "score_details",
                    models.JSONField(blank=True, null=True, verbose_name="评分详情"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="反馈信息")),
                (
                    "should_retry",
                    models.BooleanField(default=False, verbose_name="是否重试"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流会话",
                "verbose_name_plural": "工作流会话",
                "db_table": "workflow_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="workflow_se_status_ab9efa_idx",
                    )
                ],
            },
        ),
    ]
