# Generated by Django 5.2.12 on 2026-08-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("learning", "0001_initial"),
        ("learning", "0002_token_detail_replace_cost"),
        ("learning", "0003_alter_workflowexecution_status"),
        ("learning", "0004_remove_workflow_execution"),
        ("learning", "0005_workflowsession_phase_workflowsession_retry_count_and_more"),
        ("learning", "0006_workflowsession_root_thread_id"),
        ("learning", "0007_add_workflow_session_runtime_config"),
        ("learning", "0008_alter_workflowsession_knowledge_base_ids_and_more"),
        ("learning", "0009_alter_workflowquestion_unique_together_and_more"),
        ("learning", "0010_workflowsession_enable_deep_thinking_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="线程 ID"
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="工作流类型"
                    ),
                ),
                ("query", models.TextField(verbose_name="查询内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行",
                "verbose_name_plural": "工作流执行",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_type", "status", "-created_at"],
                        name="workflow_ex_workflo_22efda_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="线程 ID"
                    ),
                ),
                ("user_question", models.TextField(verbose_name="用户问题")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("waiting_for_answers", "等待答案"),
                            ("retry", "重试"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="当前步骤"
                    ),
                ),
                (
                    "learning_plan",
                    models.JSONField(blank=True, null=True, verbose_name="学习计划"),
                ),
                (
                    "quiz",
                    models.JSONField(blank=True, null=True, verbose_name="练习题"),
                ),
                (
                    "user_answers",
                    models.JSONField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="得分"),
                ),
                (
                    "score_details",
                    models.JSONField(blank=True, null=True, verbose_name="评分详情"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="反馈信息"),
                ),
                (
                    "should_retry",
                    models.BooleanField(default=False, verbose_name="是否重试"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="使用的模型"
                    ),
                ),
                (
                    "token_count",
                    models.PositiveIntegerField(default=0, verbose_name="Token 数量"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0, verbose_name="响应时间(秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "token_detail",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Token 明细"
                    ),
                ),
                (
                    "enable_deep_thinking",
                    models.BooleanField(default=False, verbose_name="是否启用深度思考"),
                ),
                (
                    "knowledge_base_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关联知识库ID列表"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大生成token数"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="用户选择的模型名称",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        default="planner", max_length=20, verbose_name="当前阶段"
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="模型提供商ID",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "root_thread_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="根工作流ID",
                    ),
                ),
                (
                    "special_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="提供商专属参数"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, null=True, verbose_name="温度参数"),
                ),
                (
                    "use_web_search",
                    models.BooleanField(default=False, verbose_name="是否启用网络查询"),
                ),
            ],
            options={
                "verbose_name": "工作流会话",
                "verbose_name_plural": "工作流会话",
                "db_table": "workflow_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="workflow_se_status_ab9efa_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_index",
                    models.IntegerField(default=0, verbose_name="第几轮"),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, verbose_name="该轮执行的 thread_id"
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(blank=True, null=True, verbose_name="该轮总分"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="反馈"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.workflowsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流练习轮次",
                "verbose_name_plural": "工作流练习轮次",
                "db_table": "workflow_attempt",
                "ordering": ["attempt_index"],
                "unique_together": {("session", "attempt_index")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.CharField(
                        help_text="如 q1_r1 表示第1轮第1题",
                        max_length=50,
                        verbose_name="题目 ID",
                    ),
                ),
                (
                    "attempt_index",
                    models.IntegerField(default=0, verbose_name="第几轮练习"),
                ),
                (
                    "question_index",
                    models.IntegerField(default=0, verbose_name="该轮第几题"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "选择题"),
                            ("fill_blank", "填空题"),
                            ("short_answer", "简答题"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("question", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项列表"),
                ),
                ("correct_answer", models.TextField(verbose_name="标准答案")),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="答案解析"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="分值")),
                (
                    "user_answer",
                    models.TextField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=None, null=True, verbose_name="是否正确"
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(blank=True, null=True, verbose_name="得分"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待答"),
                            ("answered", "已答"),
                            ("scored", "已评分"),
                            ("locked", "已锁定"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="题目状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评分时间"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.workflowsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流题目",
                "verbose_name_plural": "工作流题目",
                "db_table": "workflow_question",
                "ordering": ["attempt_index", "question_index"],
                "indexes": [
                    models.Index(
                        fields=["session", "attempt_index"],
                        name="workflow_qu_session_e776a3_idx",
                    )
                ],
                "unique_together": {("session", "question_id")},
            },
        ),
    ]
