# Generated by Django 5.2.12 on 2026-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowsession",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="反馈信息"),
        ),
    ]
