# Generated by Django 5.2.12 on 2026-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_allow_null_feedback_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowsession",
            name="cost",
            field=models.DecimalField(
                decimal_places=6, default=0, max_digits=12, verbose_name="成本(美元)"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="使用的模型"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="response_time",
            field=models.FloatField(default=0, verbose_name="响应时间(秒)"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="token_count",
            field=models.IntegerField(default=0, verbose_name="Token 数量"),
        ),
    ]
