# Generated by Django 5.2.12 on 2026-06-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_token_detail_replace_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待执行"),
                    ("running", "执行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
