# Generated by Django 5.2.12 on 2026-06-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_workflowexecution_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkflowExecution",
        ),
    ]
