# Generated by Django 5.2.12 on 2026-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_workflowsession_phase_workflowsession_retry_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowsession",
            name="root_thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="根工作流ID",
            ),
        ),
    ]
