# Generated by Django 5.2.12 on 2026-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_workflowsession_root_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowsession",
            name="enable_deep_thinking",
            field=models.BooleanField(default=False, verbose_name="是否启用深度思考"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="knowledge_base_ids",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="关联知识库ID列表"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="max_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最大生成token数"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="model_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用户选择的模型名称"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="provider_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="模型提供商ID"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="selected_mcp_servers",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="选中的MCP Server列表"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="selected_tools",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="选中的工具名称列表"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="special_params",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="提供商专属参数"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="温度参数"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="use_mcp",
            field=models.BooleanField(default=False, verbose_name="是否启用MCP工具"),
        ),
    ]
