# Generated by Django 5.2.12 on 2026-06-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_add_workflow_session_runtime_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowsession",
            name="knowledge_base_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="关联知识库ID列表"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="selected_mcp_servers",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的MCP Server列表"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="selected_tools",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的工具名称列表"
            ),
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="special_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="提供商专属参数"
            ),
        ),
    ]
