# Generated by Django 5.2.12 on 2026-07-27 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_alter_workflowsession_knowledge_base_ids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workflowquestion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workflowquestion",
            name="session",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="enable_deep_thinking",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="knowledge_base_ids",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="max_tokens",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="provider_id",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="root_thread_id",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="selected_mcp_servers",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="selected_tools",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="special_params",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="workflowsession",
            name="use_mcp",
        ),
        migrations.AlterField(
            model_name="workflowsession",
            name="token_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Token 数量"),
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="线程 ID"
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="工作流类型"
                    ),
                ),
                ("query", models.TextField(verbose_name="查询内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行",
                "verbose_name_plural": "工作流执行",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="WorkflowAttempt",
        ),
        migrations.DeleteModel(
            name="WorkflowQuestion",
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow_type", "status", "-created_at"],
                name="workflow_ex_workflo_22efda_idx",
            ),
        ),
    ]
