# Generated by Django 5.2.12 on 2026-08-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_alter_workflowquestion_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowsession",
            name="enable_deep_thinking",
            field=models.BooleanField(default=False, verbose_name="是否启用深度思考"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="knowledge_base_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="关联知识库ID列表"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="max_tokens",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最大生成token数"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="model_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用户选择的模型名称"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="phase",
            field=models.CharField(
                default="planner", max_length=20, verbose_name="当前阶段"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="provider_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="模型提供商ID"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="root_thread_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="根工作流ID",
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="special_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="提供商专属参数"
            ),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="温度参数"),
        ),
        migrations.AddField(
            model_name="workflowsession",
            name="use_web_search",
            field=models.BooleanField(default=False, verbose_name="是否启用网络查询"),
        ),
        migrations.CreateModel(
            name="WorkflowAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_index",
                    models.IntegerField(default=0, verbose_name="第几轮"),
                ),
                (
                    "thread_id",
                    models.CharField(
                        max_length=100, verbose_name="该轮执行的 thread_id"
                    ),
                ),
                (
                    "total_score",
                    models.IntegerField(blank=True, null=True, verbose_name="该轮总分"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="反馈"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.workflowsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流练习轮次",
                "verbose_name_plural": "工作流练习轮次",
                "db_table": "workflow_attempt",
                "ordering": ["attempt_index"],
                "unique_together": {("session", "attempt_index")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.CharField(
                        help_text="如 q1_r1 表示第1轮第1题",
                        max_length=50,
                        verbose_name="题目 ID",
                    ),
                ),
                (
                    "attempt_index",
                    models.IntegerField(default=0, verbose_name="第几轮练习"),
                ),
                (
                    "question_index",
                    models.IntegerField(default=0, verbose_name="该轮第几题"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "选择题"),
                            ("fill_blank", "填空题"),
                            ("short_answer", "简答题"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("question", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(blank=True, null=True, verbose_name="选项列表"),
                ),
                ("correct_answer", models.TextField(verbose_name="标准答案")),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="答案解析"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="分值")),
                (
                    "user_answer",
                    models.TextField(blank=True, null=True, verbose_name="用户答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=None, null=True, verbose_name="是否正确"
                    ),
                ),
                (
                    "points_earned",
                    models.IntegerField(blank=True, null=True, verbose_name="得分"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待答"),
                            ("answered", "已答"),
                            ("scored", "已评分"),
                            ("locked", "已锁定"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="题目状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scored_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评分时间"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.workflowsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流题目",
                "verbose_name_plural": "工作流题目",
                "db_table": "workflow_question",
                "ordering": ["attempt_index", "question_index"],
                "indexes": [
                    models.Index(
                        fields=["session", "attempt_index"],
                        name="workflow_qu_session_e776a3_idx",
                    )
                ],
                "unique_together": {("session", "question_id")},
            },
        ),
    ]
