"""
Django settings for Django_xm project - 开发环境配置

配置架构（迁移后）:
  - 真相源: apps/core/config.py (Pydantic Settings, 读取 .env / 环境变量)
  - 本文件: 仅保留 Django 框架原生设置 + 从 Pydantic 注入所需值

Generated by 'django-admin startproject' using Django 5.2.12.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# ==================== 导入统一配置（Django 无关，可安全前置导入）====================
import sys
_project_root = Path(__file__).resolve().parent.parent.parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

from Django_xm.apps.ai_engine.config import settings as app_cfg

# ==================== LangSmith 初始化 ====================
if app_cfg.langsmith_tracing and app_cfg.langsmith_api_key:
    os.environ.setdefault("LANGCHAIN_TRACING_V2", "true")
    os.environ.setdefault("LANGCHAIN_API_KEY", app_cfg.langsmith_api_key)
    os.environ.setdefault("LANGCHAIN_PROJECT", app_cfg.langsmith_project)
    os.environ.setdefault("LANGCHAIN_ENDPOINT", app_cfg.langsmith_endpoint)

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# ==================== 核心安全配置（从 Pydantic 注入）====================
SECRET_KEY = os.environ.get("SECRET_KEY", app_cfg.secret_key)
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set!")
if len(SECRET_KEY) < 50:
    import warnings
    warnings.warn(
        "SECRET_KEY should be at least 50 characters long for production use",
        UserWarning,
    )

DEBUG = app_cfg.debug

ALLOWED_HOSTS = [
    h.strip() for h in app_cfg.allowed_hosts.split(",") if h.strip()
] if app_cfg.allowed_hosts else ["localhost", "127.0.0.1"]

# ==================== 应用注册 ====================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "Django_xm.apps.users",
    "Django_xm.apps.core",
    "Django_xm.apps.ai_engine",
    "Django_xm.apps.tools",
    "Django_xm.apps.chat",
    "Django_xm.apps.knowledge",
    "Django_xm.apps.learning",
    "Django_xm.apps.research",
    "Django_xm.apps.analytics",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "Django_xm.apps.core.middleware.CurrentRequestMiddleware",
    "Django_xm.apps.core.middleware.SessionSecurityMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "Django_xm.apps.core.middleware.RequestTimeoutMiddleware",
    "Django_xm.apps.core.middleware.RequestLoggingMiddleware",
    "Django_xm.apps.core.middleware.CacheControlMiddleware",
    "Django_xm.apps.core.middleware.RateLimitMiddleware",
    "Django_xm.apps.analytics.middleware.AnalyticsMiddleware",
    "Django_xm.apps.core.middleware.SecurityHeadersMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in app_cfg.cors_allowed_origins.split(",") if o.strip()
] or ["http://localhost:3000", "http://localhost:8000"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = [
    "accept", "accept-encoding", "authorization", "content-type",
    "dnt", "origin", "user-agent", "x-csrftoken", "x-requested-with",
]
CORS_EXPOSE_HEADERS = ["content-disposition", "X-Captcha-Key", "X-Request-Duration"]

ROOT_URLCONF = "Django_xm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Django_xm.wsgi.application"

# ==================== 数据库 ====================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": os.environ.get("DB_HOST", app_cfg.db_host),
        "PORT": int(os.environ.get("DB_PORT", str(app_cfg.db_port))),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "NAME": os.environ.get("DB_NAME", app_cfg.db_name),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "connect_timeout": 10,
            "read_timeout": 30,
            "write_timeout": 30,
        },
    }
}

if not DATABASES["default"]["USER"]:
    raise ValueError("DB_USER environment variable is not set!")
if not DATABASES["default"]["PASSWORD"]:
    raise ValueError("DB_PASSWORD environment variable is not set!")
if not DATABASES["default"]["NAME"]:
    raise ValueError("DB_NAME environment variable is not set!")

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in app_cfg.csrf_trusted_origins.split(",") if o.strip()
] or CORS_ALLOWED_ORIGINS

LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# ==================== 缓存（从 Pydantic 注入 Redis 配置）====================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', app_cfg.redis_url),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'PASSWORD': os.environ.get('REDIS_PASSWORD', app_cfg.redis_password),
        },
        'TIMEOUT': app_cfg.redis_default_timeout,
        'KEY_PREFIX': 'langchain_xm',
    },
    'chat_sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_CHAT_URL', app_cfg.redis_chat_url),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 100,
                'retry_on_timeout': True,
            },
            'PASSWORD': os.environ.get('REDIS_PASSWORD', app_cfg.redis_password),
        },
        'TIMEOUT': app_cfg.redis_chat_timeout,
        'KEY_PREFIX': 'chat_session',
    }
}

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = PROJECT_ROOT / "data"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'Django_xm.apps.users.backends.UsernameMobileAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ==================== DRF 配置 ====================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "EXCEPTION_HANDLER": "Django_xm.apps.common.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "Django_xm.apps.core.throttling.AnonymousRateThrottle",
        "Django_xm.apps.core.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anonymous": "100/min",
        "user": "200/min",
        "login": "5/min",
        "chat_stream": "30/min",
        "sensitive": "10/min",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "SEARCH_PARAM": "search",
    "ORDERING_PARAM": "ordering",
    "NUM_PROXIES": 0,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "COERCE_DECIMAL_TO_STRING": False,
    "UPLOADED_FILES_USE_URL": True,
    "JSON_UNDERSCOREIZE": {
        "no_underscore_before_number": True,
    },
}

# ==================== JWT（从 Pydantic 注入有效期）====================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=app_cfg.jwt_access_token_lifetime_days),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=app_cfg.jwt_refresh_token_lifetime_days),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    "TOKEN_OBTAIN_SERIALIZER": "Django_xm.apps.users.serializers.MyTokenObtainPairSerializer",
    'UPDATE_LAST_LOGIN': True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": f"{app_cfg.app_name} API",
    "DESCRIPTION": f"{app_cfg.app_name} 智能学习 & 研究助手 API",
    "VERSION": app_cfg.app_version,
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {"name": "API Support"},
    "LICENSE": {"name": "MIT License"},
}

# ==================== 日志（Django 原生 LOGGING 配置保持不变）====================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)s %(module)s %(lineno)d %(message)s"
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR.parent, "logs", "django.log"),
            "maxBytes": 300 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "propagate": True,
        },
        "langchain": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ==================== Celery（从 Pydantic 注入）====================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', app_cfg.celery_broker_url)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', app_cfg.celery_result_backend)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = app_cfg.celery_task_time_limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_RESULT_EXPIRES = 86400
CELERY_BEAT_SCHEDULE_FILENAME = str(PROJECT_ROOT / 'data' / 'celerybeat' / 'celerybeat-schedule')

CELERY_BEAT_SCHEDULE = {
    'check-storage-alerts-every-hour': {
        'task': 'chat.check_storage_alerts',
        'schedule': crontab(minute=10),
    },
    'index-old-attachments-daily': {
        'task': 'chat.index_old_attachments',
        'schedule': crontab(hour=2, minute=0),
    },
    'cleanup-expired-attachments-daily': {
        'task': 'chat.cleanup_expired_attachments',
        'schedule': crontab(hour=int(os.environ.get('ATTACHMENT_CLEANUP_HOUR', 3)), minute=0),
    },
}

# ==================== 安全配置（开发环境宽松）====================
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = app_cfg.session_cookie_age

# ==================== 文件上传限制（从 Pydantic 注入）====================
_upload_limit = app_cfg.upload_max_memory_size_mb * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = _upload_limit
FILE_UPLOAD_MAX_MEMORY_SIZE = _upload_limit
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# ==================== 邮件（从 Pydantic 注入）====================
EMAIL_BACKEND = app_cfg.email_backend
DEFAULT_FROM_EMAIL = app_cfg.default_from_email
SERVER_EMAIL = app_cfg.default_from_email

# ==================== 国际化 ====================
LOCALE_PATHS = [BASE_DIR / 'locale']

# ==================== 向后兼容（从 Pydantic 注入）====================
APP_NAME = app_cfg.app_name
APP_VERSION = app_cfg.app_version

# ==================== 数据目录初始化（从 Pydantic 注入路径）====================
DATA_DIR = PROJECT_ROOT / app_cfg.data_dir
DOCUMENTS_DIR = PROJECT_ROOT / app_cfg.data_documents_path
INDEXES_DIR = PROJECT_ROOT / app_cfg.vector_store_path
UPLOADS_DIR = PROJECT_ROOT / app_cfg.data_uploads_path

for directory in [DATA_DIR, DOCUMENTS_DIR, INDEXES_DIR, UPLOADS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

# ==================== 附件生命周期管理配置 ====================
ATTACHMENT_DEFAULT_RETENTION_DAYS = int(os.environ.get('ATTACHMENT_DEFAULT_RETENTION_DAYS', 30))
ATTACHMENT_CLEANUP_HOUR = int(os.environ.get('ATTACHMENT_CLEANUP_HOUR', 3))
ATTACHMENT_ARCHIVE_ENABLED = os.environ.get('ATTACHMENT_ARCHIVE_ENABLED', 'true').lower() == 'true'
ATTACHMENT_ARCHIVE_DIR = PROJECT_ROOT / os.environ.get('ATTACHMENT_ARCHIVE_DIR', 'data/archives')
ATTACHMENT_ARCHIVE_AFTER_DAYS = int(os.environ.get('ATTACHMENT_ARCHIVE_AFTER_DAYS', 60))
ATTACHMENT_STORAGE_WARNING_THRESHOLD = float(os.environ.get('ATTACHMENT_STORAGE_WARNING_THRESHOLD', 80))
ATTACHMENT_STORAGE_CRITICAL_THRESHOLD = float(os.environ.get('ATTACHMENT_STORAGE_CRITICAL_THRESHOLD', 95))
ATTACHMENT_DEDUP_ENABLED = os.environ.get('ATTACHMENT_DEDUP_ENABLED', 'true').lower() == 'true'
ATTACHMENT_MAX_TOTAL_SIZE_MB = int(os.environ.get('ATTACHMENT_MAX_TOTAL_SIZE_MB', 5120))

if ATTACHMENT_ARCHIVE_ENABLED:
    ATTACHMENT_ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)

# ==================== 静态文件 ====================
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
