# Generated by Django 5.2.12 on 2026-08-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def merge_knowledge_base_fields(apps, schema_editor):
    """合并 selected_knowledge_base（单选）到 selected_knowledge_bases（多选）。

    自 0006_merge_knowledge_base_fields 内联（数字开头模块无法被 import）。
    """
    ChatSession = apps.get_model('chat', 'ChatSession')
    for session in ChatSession.objects.filter(selected_knowledge_base__isnull=False).exclude(selected_knowledge_base=''):
        # 仅当 selected_knowledge_bases 为空时才合并
        if not session.selected_knowledge_bases:
            session.selected_knowledge_bases = [session.selected_knowledge_base]
            session.save(update_fields=['selected_knowledge_bases'])


def reverse_merge(apps, schema_editor):
    # 反向操作不需要，保留原字段值
    pass


def backfill_assistant_versions(apps, schema_editor):
    """为 role='assistant' 且 versions 为空的 ChatMessage 回填单元素 versions 数组。

    自 0012_backfill_assistant_message_versions 内联。
    将当前 content/tool_calls/sources/reasoning/model 包装为 versions 的唯一元素，
    current_version 置为 0。user/system 消息不处理（versions 保持空数组）。
    """
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    queryset = ChatMessage.objects.filter(role='assistant', versions=[])
    to_update = []
    for message in queryset.iterator():
        message.versions = [{
            "content": message.content,
            "tool_calls": message.tool_calls or [],
            "sources": message.sources or [],
            "reasoning": message.reasoning or "",
            "created_at": message.created_at.isoformat() if message.created_at else "",
            "model": message.model or "",
        }]
        message.current_version = 0
        to_update.append(message)

    if to_update:
        ChatMessage.objects.bulk_update(
            to_update,
            ['versions', 'current_version'],
            batch_size=500,
        )


def reverse_backfill_assistant_versions(apps, schema_editor):
    """回滚：将 assistant 消息的 versions 清空为 []，current_version 重置为 0。

    仅清空由正向迁移写入的单元素 versions，不恢复原始字段（content 等保持现状，
    因为正向迁移未修改这些字段）。
    """
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    queryset = ChatMessage.objects.filter(role='assistant')
    to_update = []
    for message in queryset.iterator():
        message.versions = []
        message.current_version = 0
        to_update.append(message)

    if to_update:
        ChatMessage.objects.bulk_update(
            to_update,
            ['versions', 'current_version'],
            batch_size=500,
        )


class Migration(migrations.Migration):

    replaces = [('chat', '0001_initial'), ('chat', '0002_add_research_task_id_to_chatmessage'), ('chat', '0003_token_detail_replace_cost'), ('chat', '0004_add_selected_knowledge_bases'), ('chat', '0005_add_approval_field'), ('chat', '0006_merge_knowledge_base_fields'), ('chat', '0007_add_is_streaming_field'), ('chat', '0008_remove_plan_chain_of_thought'), ('chat', '0009_alter_chatsession_selected_knowledge_bases'), ('chat', '0010_alter_chatmessage_approval_and_more'), ('chat', '0011_alter_chatmessage_current_version'), ('chat', '0012_backfill_assistant_message_versions'), ('chat', '0013_add_selected_tools_to_session'), ('chat', '0014_remove_chatmessage_is_streaming_and_more'), ('chat', '0015_remove_plan_chain_of_thought_dead_fields'), ('chat', '0016_chatmessage_chain_of_thought_chatmessage_plan'), ('chat', '0017_add_is_streaming'), ('chat', '0018_remove_tool_calls_null'), ('chat', '0019_chatmessage_is_finalized'), ('chat', '0020_chatmessage_subagent_contents')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(default='新对话', max_length=200, verbose_name='会话标题')),
                ('mode', models.CharField(choices=[('agent', '代理'), ('deep-research', '深度研究')], default='agent', max_length=50, verbose_name='对话模式')),
                ('selected_knowledge_base', models.CharField(blank=True, max_length=200, null=True, verbose_name='选中的知识库')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_session',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], db_index=True, default='user', max_length=20, verbose_name='角色')),
                ('content', models.TextField(blank=True, max_length=50000, verbose_name='内容')),
                ('sources', models.JSONField(blank=True, default=list, null=True, verbose_name='来源')),
                ('plan', models.JSONField(blank=True, default=dict, null=True, verbose_name='计划')),
                ('chain_of_thought', models.JSONField(blank=True, default=list, null=True, verbose_name='思维链')),
                ('tool_calls', models.JSONField(blank=True, default=list, null=True, verbose_name='工具调用')),
                ('reasoning', models.JSONField(blank=True, default=dict, null=True, verbose_name='推理')),
                ('suggestions', models.JSONField(blank=True, default=list, null=True, verbose_name='建议问题')),
                ('versions', models.JSONField(blank=True, default=list, null=True, verbose_name='消息版本')),
                ('current_version', models.IntegerField(default=0, verbose_name='当前版本索引')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用的模型')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token 数量')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='成本(美元)')),
                ('response_time', models.FloatField(default=0, verbose_name='响应时间(秒)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'created_at'], name='chat_sessio_user_id_d7b086_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['mode'], name='chat_sessio_mode_ff6102_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chat_messag_role_9cd150_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role', 'created_at'], name='chat_messag_session_2d10e9_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='research_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='关联深度研究任务ID'),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='cost',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='token_detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Token 明细'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_knowledge_bases',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='选中的知识库列表'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='approval',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='审批数据'),
        ),
        migrations.RunPython(
            code=merge_knowledge_base_fields,
            reverse_code=reverse_merge,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='标记该消息是否正在进行流式输出，用于前端刷新后判断是否需要恢复', verbose_name='是否正在流式输出'),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chain_of_thought',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='plan',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='selected_knowledge_bases',
            field=models.JSONField(blank=True, default=list, verbose_name='选中的知识库列表'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='approval',
            field=models.JSONField(blank=True, default=dict, verbose_name='审批数据'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='reasoning',
            field=models.JSONField(blank=True, default=dict, verbose_name='推理'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, verbose_name='建议问题'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list, verbose_name='工具调用'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='versions',
            field=models.JSONField(blank=True, default=list, verbose_name='消息版本'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='current_version',
            field=models.PositiveIntegerField(default=0, help_text='当前展示的版本索引，指向 versions 数组的位置', verbose_name='当前版本索引'),
        ),
        migrations.RunPython(
            code=backfill_assistant_versions,
            reverse_code=reverse_backfill_assistant_versions,
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_streaming',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='approval',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='审批数据'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='reasoning',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='推理'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='建议问题'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Token 数量'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='versions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='消息版本'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='selected_knowledge_bases',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='选中的知识库列表'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chain_of_thought',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='思维链'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='plan',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='计划'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='标记该消息是否正在进行流式输出，用于前端刷新后判断是否需要恢复', verbose_name='是否正在流式输出'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list, verbose_name='工具调用'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='标记该消息的当前选中版本是否已固化为本轮主消息（发送新消息/超时触发）；固化后禁止重新生成', verbose_name='是否已固化版本'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='subagent_contents',
            field=models.JSONField(blank=True, default=dict, verbose_name='子代理图层正文'),
        ),
    ]
