# Generated by Django 5.2.12 on 2026-04-27 14:03

import Django_xm.apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新对话", max_length=200, verbose_name="会话标题"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("basic-agent", "基础代理"),
                            ("deep-research", "深度研究"),
                            ("rag", "RAG检索"),
                            ("workflow", "工作流"),
                        ],
                        default="basic-agent",
                        max_length=50,
                        verbose_name="对话模式",
                    ),
                ),
                (
                    "selected_knowledge_base",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="选中的知识库",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话",
                "db_table": "chat_session",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, max_length=50000, verbose_name="内容"),
                ),
                (
                    "sources",
                    models.JSONField(blank=True, default=list, verbose_name="来源"),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="计划"
                    ),
                ),
                (
                    "chain_of_thought",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="思维链"
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(blank=True, default=list, verbose_name="工具调用"),
                ),
                (
                    "reasoning",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="推理"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(blank=True, default=list, verbose_name="建议问题"),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="上下文信息"
                    ),
                ),
                (
                    "versions",
                    models.JSONField(blank=True, default=list, verbose_name="消息版本"),
                ),
                (
                    "current_version",
                    models.IntegerField(default=0, verbose_name="当前版本索引"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="使用的模型"
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(default=0, verbose_name="Token 数量"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="成本(美元)",
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(default=0, verbose_name="响应时间(秒)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                        verbose_name="会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=Django_xm.apps.chat.models.chat_attachment_upload_path,
                        verbose_name="文件",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME类型"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatmessage",
                        verbose_name="消息",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatsession",
                        verbose_name="会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天附件",
                "verbose_name_plural": "聊天附件",
                "db_table": "chat_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "created_at"], name="chat_sessio_user_id_d7b086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["mode"], name="chat_sessio_mode_ff6102_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_4940cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="chat_messag_role_9cd150_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "role", "created_at"],
                name="chat_messag_session_2d10e9_idx",
            ),
        ),
    ]
