# Generated by Django 5.2.12 on 2026-08-20 02:47

from django.db import migrations, models


def normalize_jsonfield_null(apps, schema_editor):
    """dj-18：存量 NULL 归一为空容器。

    list 字段 → []，dict 字段 → {}。先于 AlterField 去掉 null=True 执行，
    保证非空约束在存量库上成立（__isnull 命中 SQL NULL）。
    """
    ChatSession = apps.get_model("chat", "ChatSession")
    ChatMessage = apps.get_model("chat", "ChatMessage")

    ChatSession.objects.filter(selected_knowledge_bases__isnull=True).update(selected_knowledge_bases=[])

    list_fields = ("sources", "chain_of_thought", "suggestions", "versions")
    dict_fields = ("plan", "approval", "reasoning")
    for field in list_fields:
        ChatMessage.objects.filter(**{f"{field}__isnull": True}).update(**{field: []})
    for field in dict_fields:
        ChatMessage.objects.filter(**{f"{field}__isnull": True}).update(**{field: {}})


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_squashed"),
    ]

    operations = [
        migrations.RunPython(normalize_jsonfield_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chatmessage",
            name="approval",
            field=models.JSONField(blank=True, default=dict, verbose_name="审批数据"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="chain_of_thought",
            field=models.JSONField(blank=True, default=list, verbose_name="思维链"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="plan",
            field=models.JSONField(blank=True, default=dict, verbose_name="计划"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="reasoning",
            field=models.JSONField(blank=True, default=dict, verbose_name="推理"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(blank=True, default=list, verbose_name="来源"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(blank=True, default=list, verbose_name="建议问题"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="versions",
            field=models.JSONField(blank=True, default=list, verbose_name="消息版本"),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="selected_knowledge_bases",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的知识库列表"
            ),
        ),
    ]
