# Generated by Django 5.2.12 on 2026-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="来源"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="建议问题"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="工具调用"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="versions",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="消息版本"
            ),
        ),
    ]
