# Generated by Django 5.2.12 on 2026-05-03 15:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatmessage_sources_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentCleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("cleanup", "定时清理"),
                            ("archive", "归档"),
                            ("manual_delete", "手动删除"),
                            ("restore", "恢复"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "files_processed",
                    models.PositiveIntegerField(default=0, verbose_name="处理文件数"),
                ),
                (
                    "files_deleted",
                    models.PositiveIntegerField(default=0, verbose_name="删除文件数"),
                ),
                (
                    "files_archived",
                    models.PositiveIntegerField(default=0, verbose_name="归档文件数"),
                ),
                (
                    "files_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="跳过文件数"),
                ),
                (
                    "space_freed",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="释放空间(字节)"
                    ),
                ),
                (
                    "space_archived",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="归档空间(字节)"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="错误列表"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        default="system",
                        max_length=100,
                        verbose_name="触发来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "附件清理日志",
                "verbose_name_plural": "附件清理日志",
                "db_table": "chat_attachment_cleanup_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("critical", "严重")],
                        max_length=20,
                        verbose_name="告警级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="告警状态",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=500, verbose_name="存储路径"),
                ),
                (
                    "total_space",
                    models.PositiveBigIntegerField(verbose_name="总空间(字节)"),
                ),
                (
                    "used_space",
                    models.PositiveBigIntegerField(verbose_name="已用空间(字节)"),
                ),
                ("usage_percent", models.FloatField(verbose_name="使用率(%)")),
                ("threshold_percent", models.FloatField(verbose_name="阈值(%)")),
                ("message", models.TextField(blank=True, verbose_name="告警消息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "存储空间告警",
                "verbose_name_plural": "存储空间告警",
                "db_table": "chat_storage_alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="归档时间"),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="archived_path",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="归档路径"
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="file_hash",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="文件SHA256哈希"
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="last_accessed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="最后访问时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="reference_count",
            field=models.PositiveIntegerField(default=1, verbose_name="引用计数"),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="retention_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="自定义保留天数"
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "活跃"),
                    ("archived", "已归档"),
                    ("pending_delete", "待删除"),
                    ("deleted", "已删除"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="附件状态",
            ),
        ),
        migrations.AddIndex(
            model_name="chatattachment",
            index=models.Index(
                fields=["status", "created_at"], name="chat_attach_status_6acc2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatattachment",
            index=models.Index(
                fields=["last_accessed_at"], name="chat_attach_last_ac_77829c_idx"
            ),
        ),
    ]
