# Generated by Django 5.2.12 on 2026-05-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_add_research_task_id_to_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="cost",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="token_detail",
            field=models.JSONField(blank=True, default=dict, verbose_name="Token 明细"),
        ),
    ]
