# Generated by Django 5.2.12 on 2026-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_attachment_lifecycle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatattachment",
            name="archived_at",
        ),
        migrations.RemoveField(
            model_name="chatattachment",
            name="archived_path",
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="入库时间"),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="indexed_path",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="向量索引路径"
            ),
        ),
        migrations.AlterField(
            model_name="chatattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "活跃"),
                    ("indexed", "已入库"),
                    ("pending_delete", "待删除"),
                    ("deleted", "已删除"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="附件状态",
            ),
        ),
    ]
