# Generated by Django 5.2.12 on 2026-06-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_token_detail_replace_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="selected_knowledge_bases",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="选中的知识库列表"
            ),
        ),
    ]
