# Generated by Django 5.2.12 on 2026-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatattachment_archived_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentcleanuplog",
            name="action",
            field=models.CharField(
                choices=[
                    ("cleanup", "定时清理"),
                    ("index", "入库"),
                    ("unindex", "移除入库"),
                    ("manual_delete", "手动删除"),
                    ("restore", "恢复"),
                    ("permanent_delete", "永久删除"),
                    ("restore_from_trash", "从回收站恢复"),
                ],
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="attachmentcleanuplog",
            name="files_archived",
            field=models.PositiveIntegerField(default=0, verbose_name="入库文件数"),
        ),
        migrations.AlterField(
            model_name="attachmentcleanuplog",
            name="space_archived",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="入库空间(字节)"
            ),
        ),
    ]
