# Generated by Django 5.2.12 on 2026-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_selected_knowledge_bases"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="approval",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="审批数据"
            ),
        ),
    ]
