# Generated by Django 5.2.12 on 2026-06-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_merge_knowledge_base_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_streaming",
            field=models.BooleanField(
                default=False,
                help_text="标记该消息是否正在进行流式输出，用于前端刷新后判断是否需要恢复",
                verbose_name="是否正在流式输出",
            ),
        ),
    ]
