# Generated by Django 5.2.12 on 2026-04-18 03:45

import Django_xm.apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatsession_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=Django_xm.apps.chat.models.chat_attachment_upload_path,
                        verbose_name="文件",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME类型"
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天附件",
                "verbose_name_plural": "聊天附件",
                "db_table": "chat_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "role", "created_at"],
                name="chat_messag_session_2d10e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["mode"], name="chat_sessio_mode_ff6102_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                fields=("session_id",), name="unique_session_id"
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatmessage",
                verbose_name="消息",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatsession",
                verbose_name="会话",
            ),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
    ]
