# Generated by Django 5.2.12 on 2026-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_chat_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="context",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="上下文信息"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(blank=True, default=list, verbose_name="建议问题"),
        ),
    ]
