# Generated by Django 5.2.12 on 2026-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_is_streaming_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="chain_of_thought",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="plan",
        ),
    ]
