# Generated by Django 5.2.12 on 2026-06-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_remove_plan_chain_of_thought"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="selected_knowledge_bases",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的知识库列表"
            ),
        ),
    ]
