# Generated by Django 5.2.12 on 2026-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_chatsession_selected_knowledge_bases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="approval",
            field=models.JSONField(blank=True, default=dict, verbose_name="审批数据"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="reasoning",
            field=models.JSONField(blank=True, default=dict, verbose_name="推理"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(blank=True, default=list, verbose_name="来源"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(blank=True, default=list, verbose_name="建议问题"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(blank=True, default=list, verbose_name="工具调用"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="versions",
            field=models.JSONField(blank=True, default=list, verbose_name="消息版本"),
        ),
    ]
