# Generated by Django 5.2.12 on 2026-06-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_chatmessage_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="current_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="当前展示的版本索引，指向 versions 数组的位置",
                verbose_name="当前版本索引",
            ),
        ),
    ]
