# Generated by Django 5.2.12 on 2026-06-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_backfill_assistant_message_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="selected_tools",
            field=models.JSONField(
                blank=True, default=list, verbose_name="选中的工具名称列表"
            ),
        ),
    ]
