# Generated by Django 5.2.12 on 2026-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_add_selected_tools_to_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="is_streaming",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="selected_tools",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chain_of_thought",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="思维链"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="plan",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="计划"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="approval",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="审批数据"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="reasoning",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="推理"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="来源"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="suggestions",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="建议问题"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="token_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Token 数量"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="工具调用"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="versions",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="消息版本"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="selected_knowledge_bases",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="选中的知识库列表"
            ),
        ),
    ]
