# Generated by Django 5.2.12 on 2026-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_remove_chatmessage_is_streaming_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="chain_of_thought",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="plan",
        ),
    ]
