# Generated by Django 5.2.12 on 2026-08-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_remove_plan_chain_of_thought_dead_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="chain_of_thought",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="思维链"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="plan",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="计划"
            ),
        ),
    ]
