# Generated by Django 5.2.12 on 2026-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_add_is_streaming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="tool_calls",
            field=models.JSONField(blank=True, default=list, verbose_name="工具调用"),
        ),
    ]
