# Generated by Django 5.2.12 on 2026-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_remove_tool_calls_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_finalized",
            field=models.BooleanField(
                default=False,
                help_text="标记该消息的当前选中版本是否已固化为本轮主消息（发送新消息/超时触发）；固化后禁止重新生成",
                verbose_name="是否已固化版本",
            ),
        ),
    ]
