# Generated by Django 5.2.12 on 2026-08-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_chatmessage_is_finalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="subagent_contents",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="子代理图层正文"
            ),
        ),
    ]
