# Generated by Django 5.2.12 on 2026-06-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="提供商ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="传给 init_chat_model 的 model_provider 值，如 openai/anthropic/ollama/deepseek/groq",
                        max_length=50,
                        verbose_name="LangChain provider类型",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="图标"
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="", max_length=100, verbose_name="默认模型名"
                    ),
                ),
                (
                    "api_key_env",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 OPENAI_API_KEY，本地 provider 留空",
                        max_length=100,
                        null=True,
                        verbose_name="API Key 环境变量名",
                    ),
                ),
                (
                    "api_key_attr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 openai_api_key，本地 provider 留空",
                        max_length=100,
                        null=True,
                        verbose_name="API Key settings 属性名",
                    ),
                ),
                (
                    "base_url_attr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Base URL settings 属性名",
                    ),
                ),
                (
                    "model_attr",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="模型名 settings 属性名",
                    ),
                ),
                (
                    "special_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DeepSeek thinking/reasoning_effort 等",
                        verbose_name="特殊参数配置",
                    ),
                ),
                (
                    "presets",
                    models.JSONField(blank=True, default=dict, verbose_name="预设配置"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="值越小越靠前", verbose_name="排序权重"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "LLM 提供商",
                "verbose_name_plural": "LLM 提供商",
                "db_table": "ai_engine_provider",
                "ordering": ["sort_order", "provider_id"],
            },
        ),
        migrations.CreateModel(
            name="EmbeddingProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="提供商ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "factory_path",
                    models.CharField(
                        help_text="创建 Embedding 实例的 Python 函数路径，系统通过 importlib 动态调用。创建后不可修改。",
                        max_length=200,
                        verbose_name="工厂函数路径",
                    ),
                ),
                (
                    "key_attr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="本地 provider 留空",
                        max_length=100,
                        null=True,
                        verbose_name="API Key settings 属性名",
                    ),
                ),
                (
                    "dimension",
                    models.IntegerField(
                        default=0,
                        help_text="模型实际输出维度。仅 MRL 模型（nomic-embed-text / qwen3-embedding / embeddinggemma 等）可调整；非 MRL 模型此字段由原生最大维度锁定，不可修改。",
                        verbose_name="输出维度",
                    ),
                ),
                (
                    "supported_params",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="如 ['batch_size', 'model']",
                        verbose_name="支持的参数列表",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Embedding 提供商",
                "verbose_name_plural": "Embedding 提供商",
                "db_table": "ai_engine_embedding_provider",
                "ordering": ["sort_order", "provider_id"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如 gpt-4o-mini, deepseek-v4-flash",
                        max_length=100,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="如 ['tool_calling', 'streaming', 'deep_thinking']",
                        verbose_name="能力列表",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="ai_engine.aiprovider",
                        verbose_name="所属提供商",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM 模型",
                "verbose_name_plural": "LLM 模型",
                "db_table": "ai_engine_model",
                "ordering": ["provider", "sort_order", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
    ]
