# Generated by Django 5.2.12 on 2026-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0008_embedding_config_foreign_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embeddingproviderconfig",
            name="supported_dimensions",
        ),
    ]
