# Generated by Django 5.2.12 on 2026-07-27 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0009_remove_supported_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
    ]
