# Generated by Django 5.2.12 on 2026-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0011_subagentinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subagentinstance",
            name="pending_interrupt_info",
            field=models.JSONField(
                blank=True,
                help_text="interrupt 审批 payload（批量结构：interrupt_type/interrupt_id/requests:[{tool_call_id/tool_name/args/risk_level/reason}]）",
                null=True,
                verbose_name="中断信息",
            ),
        ),
    ]
