# Generated by Django 5.2.12 on 2026-04-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "index_name",
                    models.CharField(max_length=100, verbose_name="索引名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="文档数量"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_indexes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档索引",
                "verbose_name_plural": "文档索引",
                "db_table": "rag_document_index",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("txt", "TXT"),
                            ("md", "Markdown"),
                            ("csv", "CSV"),
                            ("docx", "Word"),
                            ("xlsx", "Excel"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "chunk_count",
                    models.IntegerField(default=0, verbose_name="分块数量"),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="knowledge.documentindex",
                        verbose_name="所属索引",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "db_table": "rag_document",
            },
        ),
        migrations.AddIndex(
            model_name="documentindex",
            index=models.Index(
                fields=["user", "-updated_at"], name="rag_documen_user_id_448997_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentindex",
            unique_together={("user", "index_name")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["index", "-created_at"], name="rag_documen_index_i_fc56e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_type"], name="rag_documen_file_ty_6a0bd2_idx"
            ),
        ),
    ]
