# Generated by Django 5.2.12 on 2026-06-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="索引名称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "空索引"),
                            ("building", "构建中"),
                            ("ready", "就绪"),
                            ("updating", "更新中"),
                            ("error", "错误"),
                        ],
                        default="empty",
                        max_length=20,
                        verbose_name="索引状态",
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        default="pgvector", max_length=50, verbose_name="存储类型"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Embedding 模型",
                    ),
                ),
                (
                    "embedding_dimension",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Embedding 维度"
                    ),
                ),
                (
                    "num_documents",
                    models.IntegerField(default=0, verbose_name="文档数量"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="扩展元数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_metadata",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "索引元数据",
                "verbose_name_plural": "索引元数据",
                "db_table": "knowledge_index_metadata",
                "indexes": [
                    models.Index(fields=["user", "status"], name="idx_user_status"),
                    models.Index(fields=["name"], name="idx_name"),
                ],
            },
        ),
    ]
