# Generated by Django 5.2.12 on 2026-06-04 11:57

import json
from pathlib import Path

from django.db import migrations
from django.conf import settings


def load_existing_metadata(apps, schema_editor):
    IndexMetadata = apps.get_model('knowledge', 'IndexMetadata')
    base_path = Path(getattr(settings, 'VECTOR_STORE_PATH', 'data/indexes'))

    if not base_path.exists():
        return

    for metadata_file in base_path.glob('*/metadata.json'):
        try:
            with open(metadata_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            name = data.get('name', metadata_file.parent.name)
            # 解析 user_id：索引名格式为 user_{id}_{kb_name}
            user_id = None
            parts = name.split('_', 2)
            if len(parts) >= 3 and parts[0] == 'user':
                try:
                    user_id = int(parts[1])
                except ValueError:
                    pass

            IndexMetadata.objects.update_or_create(
                name=name,
                defaults={
                    'user_id': user_id,
                    'status': 'ready' if data.get('num_documents', 0) > 0 else 'empty',
                    'store_type': data.get('store_type', 'pgvector'),
                    'description': data.get('description', ''),
                    'embedding_model': data.get('embedding_model', ''),
                    'embedding_dimension': data.get('embedding_dimension'),
                    'num_documents': data.get('num_documents', 0),
                    'metadata_json': data,
                }
            )
        except Exception as e:
            print(f"迁移 metadata 失败: {metadata_file} - {e}")


def reverse_load_existing_metadata(apps, schema_editor):
    """反向迁移：清空 IndexMetadata 表"""
    IndexMetadata = apps.get_model('knowledge', 'IndexMetadata')
    IndexMetadata.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_indexmetadata"),
    ]

    operations = [
        migrations.RunPython(load_existing_metadata, reverse_load_existing_metadata),
    ]
