# Generated by Django 5.2.12 on 2026-08-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_load_existing_metadata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="indexmetadata",
            name="idx_name",
        ),
    ]
