# Generated by Django 5.2.12 on 2026-06-14 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("content", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("build_command", "构建命令"),
                            ("debug_insight", "调试洞察"),
                            ("preference", "用户偏好"),
                            ("pattern", "使用模式"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("relevance_tags", models.JSONField(blank=True, default=list)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auto_memory",
                "ordering": ["-last_accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "project_id"], name="idx_auto_mem_project"
                    ),
                    models.Index(fields=["user", "source"], name="idx_auto_mem_source"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContextRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "组织策略"),
                            ("user_global", "用户全局规则"),
                            ("project", "项目规则"),
                            ("local", "本地覆盖"),
                        ],
                        default="user_global",
                        max_length=20,
                    ),
                ),
                (
                    "project_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "path_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="路径作用域 glob 模式列表，为空表示全局生效",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="同层级内优先级，数值越大越优先"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "context_rule",
                "ordering": ["-priority", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "scope", "is_active"],
                        name="idx_ctx_rule_user_scope",
                    ),
                    models.Index(
                        fields=["user", "project_id"], name="idx_ctx_rule_project"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("system_prefix", "系统前缀缓存"),
                            ("context_template", "上下文模板"),
                            ("user_template", "用户模板"),
                        ],
                        default="user_template",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="模板变量定义 [{name, description, default}]",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("token_count", models.IntegerField(default=0)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prompt_cache",
                "ordering": ["sort_order", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "cache_type", "is_active"],
                        name="idx_prompt_cache_type",
                    )
                ],
            },
        ),
    ]
