# Generated by Django 5.2.12 on 2026-08-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "context_manager",
            "0002_automemory_deleted_at_automemory_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contextrule",
            name="user",
        ),
        migrations.RemoveField(
            model_name="promptcache",
            name="user",
        ),
        migrations.DeleteModel(
            name="AutoMemory",
        ),
        migrations.DeleteModel(
            name="ContextRule",
        ),
        migrations.DeleteModel(
            name="PromptCache",
        ),
    ]
